#!/bin/bash

# System Health Check
# Compatible with Debian Linux

set -u

# ---------- Configuration ----------
readonly SCRIPT_NAME="$(basename "$0")"

# ---------- Error Handling ----------
error() {
    echo "ERROR: $*" >&2
}

require_command() {
    if ! command -v "$1" >/dev/null 2>&1; then
        error "Required command '$1' is not available."
        exit 1
    fi
}

# Check required commands
for cmd in date uptime free df ps awk; do
    require_command "$cmd"
done

# ---------- Header ----------
echo "============================================================"
echo "                 SYSTEM HEALTH CHECK"
echo "============================================================"
echo "Generated by: $SCRIPT_NAME"
echo

# ---------- Date / Time ----------
echo "------------------------------------------------------------"
echo " CURRENT DATE/TIME"
echo "------------------------------------------------------------"

if ! date '+%Y-%m-%d %H:%M:%S %Z'; then
    error "Unable to determine current date/time."
fi
echo

# ---------- Uptime ----------
echo "------------------------------------------------------------"
echo " SYSTEM UPTIME"
echo "------------------------------------------------------------"

if ! uptime -p 2>/dev/null; then
    error "Unable to determine system uptime."
fi
echo

# ---------- CPU Usage ----------
echo "------------------------------------------------------------"
echo " CPU USAGE"
echo "------------------------------------------------------------"

# Calculate CPU usage from /proc/stat over a short sampling interval.
if [[ -r /proc/stat ]]; then
    read_cpu_stats() {
        awk '/^cpu / {
            idle=$5+$6
            total=$2+$3+$4+$5+$6+$7+$8+$9+$10
            print idle, total
            exit
        }' /proc/stat
    }

    read -r idle1 total1 < <(read_cpu_stats)
    sleep 1
    read -r idle2 total2 < <(read_cpu_stats)

    if [[ -n "${idle1:-}" && -n "${total1:-}" &&
          -n "${idle2:-}" && -n "${total2:-}" &&
          "$total2" -gt "$total1" ]]; then

        cpu_usage=$(awk -v i1="$idle1" -v t1="$total1" \
                         -v i2="$idle2" -v t2="$total2" \
            'BEGIN {
                usage = 100 * (1 - (i2-i1)/(t2-t1))
                if (usage < 0) usage = 0
                if (usage > 100) usage = 100
                printf "%.1f", usage
            }')

        echo "CPU Usage: ${cpu_usage}%"
    else
        error "Unable to calculate CPU usage."
    fi
else
    error "/proc/stat is not available."
fi
echo

# ---------- Memory ----------
echo "------------------------------------------------------------"
echo " MEMORY"
echo "------------------------------------------------------------"

if memory_info=$(free -m 2>/dev/null); then
    read -r total_mem available_mem < <(
        awk '/^Mem:/ {
            print $2, $7
            exit
        }' <<< "$memory_info"
    )

    if [[ -n "${total_mem:-}" && -n "${available_mem:-}" ]]; then
        echo "Total RAM:     ${total_mem} MB"
        echo "Available RAM: ${available_mem} MB"
    else
        error "Unable to parse memory information."
    fi
else
    error "Unable to determine memory usage."
fi
echo

# ---------- Disk Usage ----------
echo "------------------------------------------------------------"
echo " DISK USAGE — ALL MOUNTED PARTITIONS"
echo "------------------------------------------------------------"

if ! df -hP; then
    error "Unable to retrieve disk usage."
fi
echo

# ---------- Top Processes ----------
echo "------------------------------------------------------------"
echo " TOP 5 PROCESSES BY CPU USAGE"
echo "------------------------------------------------------------"

if ! ps -eo pid,user,%cpu,%mem,comm --sort=-%cpu 2>/dev/null | head -n 6; then
    error "Unable to retrieve process information."
fi
echo

# ---------- Footer ----------
echo "============================================================"
echo "                 HEALTH CHECK COMPLETE"
echo "============================================================"